version: '3'
services:
  app:
    container_name: auth-service
    build: .
    ports:
      - '3003:3003'
    depends_on:
      - auth-db
    networks:
      - cspace-backend
      - auth-network
        
  auth-db:
    container_name: auth-db
    image: mongo
    ports:
      - '28003:27017'
    networks:
      - auth-network

networks:
   cspace-backend:
      external: true
   auth-network:
      external: true
